#!/usr/local/bin/perl
use strict; use warnings;
use Const::Fast 'const';
use Time::HiRes;
use Digest::SHA 'sha256_hex';
use POSIX;
use File::Path;
use File::Copy;
use File::LibMagic;
use Sys::Hostname 'hostname';
use LWP::UserAgent;
use LWP::Protocol::https;

######################################################
# DEMON - daemon summoning scroll

# INIT ###############################################
my ($path) = @ARGV;
if (not defined $path) { die ('NO ARGV1 dir'); }
if (substr($path, -1) ne "/") { $path .= '/'; }

# BIRTH ##############################################
die "STILLBORN" if ((my $birth = daemon()) != 0);

# DIRS ###############################################
# /tmp/$NAME_dump : hostside work dir

# /nfs/que/ : api que
# /nfs/node/ : daemon dir by host
# /nfs/node/DIO : DEMON CHK-IN CHK-OUT
# /nfs/cemetery/ : tombstone() dead DEMON logs

# /nfspool/g/ : XS()
# /nfspool/pool/ : XS()

# GLOBAL CONST #######################################
const my $PATH => $path;
const my $NAME => name();
const my $DUMP => $NAME.'_dump/';
const my $TOMB => $PATH.'cemetery/';
const my $NODE => hostname();
const my $QUE => $PATH.'node/'.$NODE;

const my $TODO => $TOMB.'TODO_'.$NAME;
const my $DONE => $TOMB.'DONE_'.$NAME;
const my $FAIL => $TOMB.'FAIL_'.$NAME;
const my $SHELL => $TOMB.'SHELL_'.$NAME;
const my $REP => $TOMB.'REP_'.$NAME;
const my $RAW => $TOMB.'RAW_'.$NAME;
const my $ZOMBIE => $TOMB.'ZOMBIE_'.$NAME;

const my $SLEEP => $NAME.'_SLEEP';
const my $SUICIDE => $NAME.'_SUICIDE';
const my $DIO => $PATH.'node/DIO';
const my $BIRTH => time();
const my $RATE => 100;

const my @API => ('net_get','fs_blkr','k_krip', 'fs_xtrax', 'xs_get' );
const my $SIZE => 128000;

# GLOBAL VARIABLE ####################################
my $YAY = 0;

# PREP ###############################################
chdir('/tmp/');
$SIG{INT} = \&SUICIDE;
$SIG{HUP} = \&que_up;

mkdir $DUMP or die "$DUMP FAIL\n";

open(my $Lfh, '>>', $RAW);
open(my $FAILfh, '>>', $FAIL);
open(my $DONEfh, '>>', $DONE);
open(my $TODOfh, '>>', $TODO);
$Lfh->autoflush(1);
$FAILfh->autoflush(1);
$DONEfh->autoflush(1);
$TODOfh->autoflush(1);

ping(); # host roster
dio('IN'); # net roster

printf $Lfh ("HELLOWORLD %s\n", TIME());

while (1)
{ # WORK ################################################
	my $que = que_up();
	unless (-e $que)
		{ sleep 3600; next; }
	open(my $qfh, '<', $que);
	my @QUE = readline $qfh; chomp @QUE;

	my $api = shift @QUE;

	next if (api($api, $qfh, $que) < 0);

	my $ttl = @QUE;
	my $count = 0;

	foreach (@QUE)
	{
		if (-e $SUICIDE)
    			{ SUICIDE(); }
		if (-e $SLEEP)
   	 		{ SLEEP(); }
		my $i = shift @QUE;
		my $i_start = gettimeofday();
		if (&$api($i) != 0)
			{ print $FAILfh "$i\n"; }
		printf $Lfh "%.3f %s\n", gettimeofday()-$i_start, $i;
		print $DONEfh "$i\n";
		$count++;
		if ($count % $RATE == 0)
		{
			tombstone($api, $count, $ttl);
			open(my $TODOfh, '>', $TODO);
			print $TODOfh @QUE; close $TODOfh;
		}
	}
	unlink $TODO;
}
# SUB ###########################################################
sub daemon {
   die "FAIL daemon1 $!\n" if ((my $pid = fork()) < 0);
   if ($pid != 0)
   	{ exit(0); }
   POSIX::setsid() or die "FAIL setsid $!";
   die "FAIL daemon2 $!\n" if ((my $pid2 = fork()) < 0);
   if ($pid2 != 0)
   	{ exit(0); }
   chdir('/tmp');
   umask 0;
   my $fds = 3;
   while ($fds < 1024)
      { POSIX::close($fds); $fds++;  }
   my $des = '/dev/null';
   open(STDIN, "<$des");
   open(STDOUT, ">$des");
   open(STDERR, ">$des");
   return 0;
}
sub api
{
	my ($api, $qfh, $que) = @_;
	print $Lfh "api $api\n";
	unless (/$api/, @API)
	{
		print $Lfh "FAIL_API $api\n";
		close $qfh;
		move($que, $ZOMBIE);
		return -1;
	}
	return 0;
}
sub SUICIDE
{
	my ($api, $count, $ttl) = @_;
	unlink $SUICIDE;
	printf $Lfh ("FKTHEWORLD %s\n", TIME());
	dio('OUT');
	tombstone($api, $count, $ttl);
	exit;
}
sub SLEEP
{
	my ($api, $count, $ttl) = @_;
	open(my $Sfh, '<', $SLEEP);
	my $timeout = readline $Sfh; chomp $timeout;
	print $Lfh ("$SLEEP %s %s\n", $timeout, TIME());
	close $Sfh; unlink $SLEEP;
	tombstone($api, $count, $ttl);
	sleep $timeout;
}
sub TIME
{
	my $t = localtime;
	my $mon = (split(/\s+/, $t))[1];
	my $day = (split(/\s+/, $t))[2];
	my $hour = (split(/\s+/, $t))[3];
	my $time = $mon.'_'.$day.'_'.$hour;
	return $time;
}
sub name
{
	my $id = int(rand(999));
	my $name = $NODE.'_'.$$.'_'.$id;
	return $name;
}
sub tombstone
{
	my ($api, $count, $ttl) = @_;

	open(my $LLfh, '<', $TOMB);
	my @llfh = readline $LLfh;
	my @yay = grep { /^YAY / } @llfh;
	my $yay = @yay;
	my @FACE;
	$FACE[0] = $NAME;
	my $Ttime = time();
	$FACE[1] = ((($Ttime - $BIRTH)/60)/60);
	$FACE[2] = $api.'_'.$yay.'_'.$count.'_'.$ttl;

	open(my $Tfh, '>>', $TOMB);
	printf $Tfh ("%d %s %d %s\n", $YAY, $FACE[0], $FACE[1], $FACE[2]);
}
sub dio
{
	my $dstatus = (@_);
	open(my $Dfh, '>>', $DIO);
	printf $Dfh ("%s %s %s\n", TIME(), $NAME, $dstatus);
	close $Dfh;
}
sub ping
{
	open(my $Pfh, '>>', '/tmp/PING');
	printf $Pfh "%ld %s ping!\n", time(), $$;
}
sub que_up
{
	opendir(my $dh, $QUE);
	my @ls = readdir($dh);
	return $ls[0];
}
# XS ###########################################################
sub XS
{
	my ($file) = shift;
	my ($sha) = file_digest($file) or die "couldn't sha $file";
	File::Copy::copy($file, $PATH."pool/$sha");
	my $cur = $PATH."g/g$sha";
	open(my $fh, '>>', $cur) or die "Meta File Creation FAIL $file";
	printf $fh "%s\n%s\n%s\n%s\n", 
		xsname($file),
		xspath($file),
		xssize($file),
		file_mime_encoding($file);
}
sub file_digest {
	my ($file) = @_;
	my $digester = Digest::SHA->new('sha256');
	$digester->addfile( $file, 'b' );
	return $digester->hexdigest;
}
sub xsname {
	my ($file) = @_;
	$file =~ s?^.*/??;
	return $file;
}
sub xspath {
	my ($file) = @_;
	$file =~ s?/?_?g;
	return $file; 
}
sub file_mime_encoding {
	my ($file) = @_;
	my $magic = File::LibMagic->new();
	my $info = $magic->info_from_filename($file);
	my $des = $info->{description};
	$des =~ s?[/ ]?.?g;
	$des =~ s/,/_/g;
	my $md = $info->{mime_type};
	$md =~ s?[/ ]?.?g;
	my $enc = sprintf("%s %s %s", $des, $md, $info->{encoding}); 
	return $enc;
}
sub xssize {
	my ($file) = @_;
	my $size = -s $file;
	return $size;
}
# API #############################################
sub get
{
	my ($i) = @_;
	my $ua = uagent();
	my $response = $ua->get($i, ':content_file'=>"$DUMP$i");
	print $Lfh "YAY $i\n"; $YAY++;
	XS($i) && unlink($i);
}
sub uagent
{
	my $s_ua = LWP::UserAgent->new(
		agent => "Mozilla/50.0.2",
		from => 'punxnotdead',
		timeout => 45,
	);
	return $s_ua;
}
sub blkr
{
	my ($i) = @_;
	my $block = 0;
	my $ipath = $PATH.'pool/'.$i;
	open(my $ifh, '<', "$ipath") || print $Lfh "Cant open $i: $!\n";
	binmode($ifh);
	
	while (read($ifh, $block, $SIZE))
	{
		my $bsha = sha256_hex($block);
		my $bname = $PATH.'sea/'.$bsha;
		open(my $fh, '>', "$bname");
		binmode($fh);
		print $fh $block;
		key($i, $bsha);
	}
	$YAY++;
}
sub key
{
	my ($i, $bsha) = @_;
	my $kpath = $PATH.'key/'.$i;
	open(my $kfh, '>>', "$kpath");
	print $kfh "$bsha\n";
}
sub sha
{
	my ($i) = @_;
	my ($sha) = file_digest($i);
	if ($sha ne $i)
		{ print $Lfh "ERK $i ne $sha\n"; }
	$YAY++;
}
